BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB

XXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XX XXXXXXXXXXXX
    XXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXX XXXX XXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
      XXXX
      XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXX
      XXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX
      XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX
      XXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX

XXXXXXXXXX
  BBBBBBBB