BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB

BBBBB BBBBBBB

 XXXX XXXXX XXX
XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Frakooshan Ltd') XXXXX

        XX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'Oil & Gas Training Courses Online & In-Person') XXXX

        XXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXX XXXXXXXXX
        XXXXXXXXX
    XXXXXX
XXXXXX

XXXX  XXX
XXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX  XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXXXX
            XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            
        XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX  XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
           
        XXXX
    XXXXXX
XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX X XXX XXXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXX XXX XXX XXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXX XXXXX XXXXXXXX XXXXXXXX
                XXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXX XX XXXXXXXXX XXXXXXX XXXXXXXXXXX XXX XXXXXXXXXX XXXXX XXXXXXXXXXX
                XXX XXXXXXXXXXX
            XXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX
                XXX XXXX XX XXXXXXXX XXXX XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXX XXXXX XXXXXXXX XX XXXXXX XXX XXXXX XXX
                XXXXXXX XX XXXXXXXX XXXXX XXXX XXXXXX XX XXXXX XXXXX XXX XXX XXXXX XXXXXXXX XX XXX XXXXXXXXXXX
                XXXXXXXXXX XXXXXX XXXXXXXXXXXX XX XXXXXXXXXXXX XX XXX XXXX XXXXXX XX XXXXXXX XXXXXXXX XX XXXXX
                XXXXXXXXXX XX XXXXXXXX XXXXXXXX XXXX XXXX XXX XXX XXXXXX XXXXXXX
            XXXX
            XXX XXXXX XX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    
    XXXXXX
XXXXXXXXXX


 


XXXX XXXXXX XXXXXXXXXX XXX
XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX
        XXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
        BBB BBBBBBBB BB BBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXX XX
                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXX
                     XXXXXXX
                XXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXX XXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX 
            XXXX
        BBBBBB
        XXXXXX

    XXXXXX XXXX XXXXXXXXXXXX XXX

XXXXXXXXXX
XXXX XXXXXXX XXXXXXX XXXXX XXX

XXXX XXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXX
        XXXX XXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXX
        XXXX XXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
        XXXX XXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
        XXXX XXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
    XXXXXX
XXXXXXXXXX

XXXX XXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXX XXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXX XXXXXXX X XXXXXX XXXXX XXXX X XXXX XXXXXX XXXX XXX XXX XXX XXXXXXX XXXXXXXXXX XXXXXXXX XXXXX
                XXXX XXXXXXX XX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXX XXX XX XXXXXXX XX XXX XX XXXX XXXXX
            XXXX
            XXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXX XXXXXXX X XXXXXX XXXXX XXXX X XXXX XXXXXX XXXX XXX XXX XXX XXXXXXX XXXXXXXXXX XXXXXXXX XXXXX
                XXXX XXXXXXX XX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXX XXX XX XXXXXXX XX XXX XX XXXX XXXXX
            XXXX
            XXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXX XXXXXXX X XXXXXX XXXXX XXXX X XXXX XXXXXX XXXX XXX XXX XXX XXXXXXX XXXXXXXXXX XXXXXXXX XXXXX
                XXXX XXXXXXX XX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXX XXX XX XXXXXXX XX XXX XX XXXX XXXXX
            XXXX
            XXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX
    XXXXXXXXXX

XXXXXX

BBBBBBBB