BBBB BBBBBB
XXXX XXXXXXXXXXXXXXXXXX XXXXX
    XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXX XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
            XXXXX
                XXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
                    BBBBBBBBBB
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX
                            XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXXXXX XXXXX XXXXX
                            XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX
                            XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXXXXX XXXXX XXXXX
                            XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                        XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                            XXXXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX

            XXXXX
                XXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                    XXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXX
                            XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXXXXX XXXXX XXXXX
                            XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                            XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXXXXX XXXXX XXXXX
                            XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXX
                            XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXXXXXX XXXXX XXXXX
                            XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                        XXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX