BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXX   
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX XXXX XXXXXX
            XXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX 
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXX
                BBB BBBB BB BBBBB
                XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
                        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX 
                                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXFFFFFFF F F FFXXXXX  
                            XXXXXX
                            XXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
            XXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            
        XXXXXX
    XXXXXX

XXXXXX

BBBBBBBB