BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXX   
        XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX XXXX XXXXXX
            XXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX 
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXX XX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                    
                XXXXX
                XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXXX XX XXXXXXXXXXXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXX  XXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXX
                XXX
                    FFFF
                XXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
            XXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            
            
        XXXXXX
    XXXXXX

XXXXXX
    
BBBBBBBB